version: '3'
services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: your_username_here
      MINIO_ROOT_PASSWORD: your_password_here
    volumes:
      - "/minio/data:/data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
#    networks:
#      - your_network_here
#networks:
 #your_network_here:
 #  driver: bridge
